baseURL: https://demonar.netlify.app/
languageCode: en-us
title: Demonar Africa Solutions Ltd
theme: hugo-hero-theme
params:
  google_analytics_id: ''
  homepage_meta_tags:
    meta_description: DAS ltd  is an organisation formed to provide End to End project contracting, consulting and management services that form the basic building blocks required for the implementation of a project.
    meta_og_description: DAS ltd  is an organisation formed to provide End to End project contracting, consulting and management services that form the basic building blocks required for the implementation of a project.
    meta_og_image: https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png
    meta_og_title: Demonar Africa Solutions Ltd
    meta_og_type: website
    meta_og_url: https://hugo-hero.netlify.app
    meta_twitter_card: summary
    meta_twitter_creator: '@demonar'
    meta_twitter_site: '@demonar'
menu:
  main:
    - name: Services
      url: /services/
      weight: 1
    - name: Work
      url: /work/
      weight: 2
    - name: About
      url: /about/
      weight: 3
    - name: History
      url: /history/
      weight: 3
    - name: Contact
      url: /contact/
      weight: 4
permalinks:
  pages: /:filename/
  post: /:year/:month/:day/:slug/
